#######################################################################################
# Book settings
title: ""
author: "Development Data Partnership"
copyright: "World Bank, 2020"
logo: docs/images/logo.png
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
only_build_toc_files: true

#######################################################################################
# Execution settings
execute:
  execute_notebooks: "off"
  allow_errors: true

#######################################################################################
# HTML-specific settings
html:
  favicon: _static/favicon.ico
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true
  baseurl: https://datapartnership.org
  google_analytics_id: G-4CEPYT7632
  extra_navbar: ""
  extra_footer: |
    <b>
      All content is licensed under the Development Data Partnership Legal Framework.
    </b>

#######################################################################################
# Repository settings
repository:
  url: https://github.com/datapartnership/docs

#######################################################################################
# Bibliography settings
bibtex_bibfiles:
  [
    "collections/mobility/docs/bibliography.bib",
    "collections/climate/docs/bibliography.bib",
  ]

#######################################################################################
# Sphinx settings
sphinx:
  config:
    language: en
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"

  #   #To create a custom 404 page
  #   notfound_context:
  #     body: "<h1>Page Not Found</h1>\n\n<p>Sorry, this page doesn't exist or may have been updated recently. Try the <a href='index.html'>home page 🏠 </a> or <a href='search.html'>search page 🔎 </a> to find what you are looking for.</p>"
  #   notfound_urls_prefix: "/docs/"

  # extra_extensions:
  #   - sphinx_notfound_page
